### PR TITLE
Add an option to tint menu icons

### PR DESCRIPTION
**Pull request by Evisceration**
Used to change the color of menu item icons.

- setMenuItemTintColor - Takes the color int to tint the icons with

- setMenuItemTintColorRes - Takes a resource id as parameter, resolves the color and then calls setMenuItemTintColor(resolvedColor)

Example usage:
```
            final BottomSheet.Builder builder = new BottomSheet.Builder(mActivity);
            builder.setTitle(weirdThing.getTitle())
                    .setListener(appBottomSheetListener)
                    .setMenuItemTintColor(Color.GREEN);
```

Screenshots - I am applying the tint depending on the primary color of the app

screenshot_2015-08-19-09-44-16

screenshot_2015-08-19-09-44-30

### CODE REVIEW

**Comment by Evisceration** [comment]
Added support for default tint via custom style as well :)

**Comment by Kennyc1012** [comment]
Haven't tested it, but looks okay. The one thing I would like changed is not testing the color against -1, as that is Color.WHITE. Instead, either have its default be Integer.MIN_VALUE or Color.TRANSPARENT as those shouldn't ever be used for colors.

**Comment by Evisceration** [comment]
Good catch!
I realized that later on, will update the pull request, thanks for the review.

**Comment by Evisceration** [comment]
Used Integer.MIN_VALUE as it makes more sense than Color.TRANSPARENT in my point of view.

**Comment by Kennyc1012** [comment]
One question I had about the tinting method
```java
new LightingColorFilter(Color.BLACK, mBuilder.menuItemTintColor)
```

Why are you passing Color.BLACK? Is that based on what color the icon is, and if so, will this method only work on black/dark icons? If that is the case, I would like to avoid that and use this tinting method instead 
```java
drawable.setColorFilter(color, PorterDuff.Mode.SRC_IN);
```

That method will paint whatever color on top of the icon, so any icon will work, granted darker icons won't get colored correctly, so a white icon should be supplied.

**Comment by Evisceration** [comment]
I am using this method since always to tint it and it worked on white as well as black icons.
In fact the screenshots you are seeing, the "open" icon is white and the "delete" is grey 600.

the only limitation with my method is alpha values in colors i guess.

**Comment by Evisceration** [comment]
Ok, updated sample in a seperate pull request #5, which depend on these changes.
If you decide to merge it, i will rebase the sample pull request as well.

**Pull request merged**
